### ISSUE TITLE
FastAPI Mockup

### ISSUE THREAD

**Issue by gracechoe** [zotbins/zbce_api#18]

**Comment by okyang** [comment]
@patrickanguyen this is it right? [zbce-mockup](https://github.com/patrickanguyen/zbce-mockup)

**Comment by okyang** [comment]
Was planning to close this issue, but I was also wondering if maybe you can host a quick seminar or walkthrough on this @patrickanguyen :smile:

**Comment by patrickanguyen** [comment]
Sure, I can do that. I'm balancing a lot of things rn, so maybe sometime in the future

**Comment by okyang** [comment]
For sure! Sorry didn't mean to overwhelm you. We can do this sometime after we wrap up the Python Flask Implementation
