### ISSUE TITLE
Add barcode endpoints

### ISSUE THREAD

**Issue by patrickanguyen** [zotbins/zbce_api#29]
Web & Mobile requested an endpoint where they can input a barcode and it will return the name of the product and the bin where it belongs. We have been provided an XLSX file of over 12,000 different barcodes, so it will probably be smart to make some sort of Python script to add all of the barcodes to our database. 

### Endpoint: GET /barcode/{barcode}
HTTP Status Code: 200
Barcode is in the database and is successfully found

```json
{
  "barcode" : 647669926366,
  "item_info" : "1016038 - BISCOTTI CHOCOLATE RASPBERRY",
  "waste_bin": "landfill"
}
```
HTTP Status Code: 404
Barcode is not in the database 
```json
{
  "message": "Barcode not found"
}
```

### Endpoint: POST /barcode/
**There should never be any duplicate barcodes in the database**

Example Body:
```json
  {
    "barcode" : 647669926366,
    "item_info" : "1016038 - BISCOTTI CHOCOLATE RASPBERRY",
    "waste_bin": "landfill"
  }
```
HTTP Status Code: 201 
Barcode is unique and has been added to the database

HTTP Status Code: 409 or 400 or 200 (not sure what the right status code should be)
Barcode already exists in the database and has not been added

**Comment by okyang** [comment]
@patrickanguyen @justinyue1643, just a suggestion; can we do this in the Fast API upgrade? We can work on both the fast api and finalizing the Flask version at the same time. That way I will help us transition to fast API faster. What do you all think?

**Comment by patrickanguyen** [comment]
I agree, since the barcode feature is unrelated to the other features if ZBCE API, we can start development on the fastapi version. 

I still need to think about it tho because the learning curve, our software architecture for the new api, and the web and mobile team need it by week 7-8.

I'm also thinking about just making a separate API because the barcode is unrelated to the sensor data collection cuz of the "Focus on one thing and do it well" philosophy.

**Comment by okyang** [comment]
@patrickanguyen I like that philosophy. If you want to avoid fastapi because of the learning curve (am I understanding you correctly?) then maybe what the UCI systems team can do is to modify the existing barcode api on our [internal api repo](https://github.com/zotbins/ZotBinsAPI). This is the one that is hosted on pythonanywhere. We can discuss this further on slack if needed.

**Comment by okyang** [comment]
Implemented in a forked repo https://github.com/zotbins/barcode_bank
